config/routes.rb
Rails.application.routes.draw do
	resources :products
	get 'page/home'

	get 'about', to: 'pages#about'
	get 'contact', to: 'pages#contact'

	devise_for :users

	root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product extend CarrierWave::Mount
	include Mongoid::Document
	field :title, type: String
	field :description, type: String
	field :price, type: Float
	field :main_image, type: String
	field :thumb_image, type: String

	mount_uploader :thumb_image, ProductUploader
	mount_uploader :main_image, ProductUploader

	validates :title, :description,:price, :presence => true
	validates :title, uniqueness: true
	validates :price, uniqueness: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception

    include DeviseWhitelist
    include DefaultPageContent

	def after_sign_in_path_for(resource)
		stored_location_for(resource) || products_path
	end
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
	extend ActiveSupport::Concern
	included do
		before_action :set_page_defaults
	end

	def set_page_defaults
		@page_title = "EcommerceApp | My Products"
		@seo_keywords = "Sushmitha products"
	end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
	extend ActiveSupport::Concern

	included do
		before_action :configure_permitted_parameters, if: :devise_controller?
	end
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
    layout 'product'

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :main_image, :thumb_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def image_generator(height:,width:)
		"http://placehold.it/#{height}x#{width}"
	end

	def product_img img, type
		if img
			img
		elsif type == 'thumb'
			image_generator(height: '350', width: '200')
		elsif type == 'main'
			image_generator(height: '600', width: '400')
		end
	end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-secondary bg-secondary">
	<nav class="navbar navbar-default">
		<div class="container-fluid">

			<ul class='nav navbar-nav'>
				<h2>
					<a href="/"> Ecommerce App </a>
			</h2>
			</ul>

	</nav>

			<ul class="nav navbar-nav navbar-right">
				<li><% if user_signed_in? %>
					<li><%= link_to current_user.email, user_session_path(current_user) %></li> &nbsp;
					<li><%= link_to 'Logout', destroy_user_session_path, method: :delete%></li>
					<% else %>
					<li><%= link_to 'Login', new_user_session_path %></li> &nbsp;
					<li><%= link_to 'Register', new_user_registration_path %></li>
					<% end %>
				</ul>

			</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name ='keywords' content="<%= @seo_keywords %>"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
    
  </head>

   <body>

            <div class= 'background-image'> 

            </div>
              <%= render 'layouts/header' %>
              <%= yield %>
              <%= render 'shared/application_footer'%> <!-- provides footer -->

  </body>
</html>

app/views/layouts/product.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'products', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
  
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>

<hr>

<div class="row">
	<div class="col-md-4">
		<%= image_tag "profile.jpg", width:300, height:250, alt: "profile image" %>
	</div>

	<div class="col-md-8">
	<p>E-commerce is the activity of buying or selling of products on online services or over the Internet. Electronic commerce draws on technologies such as mobile commerce, electronic funds transfer, supply chain management, Internet marketing, online transaction processing, electronic data interchange (EDI), inventory management systems, and automated data collection systems.</p>
	<p>The need for electronic commerce emerged from the need to use computers more efficiently in banks and corporations. With the increasing competition there was a need amongst organizations to increase customer satisfaction and information exchange. Electronic commerce started with the introduction of electronic funds transfer (EFT) by banks. Over time many variants of EFTs within banks were introduced like debit cards, credit cards and direct deposits.It can help organizations do business 7 days a week and 24 hours a day.</p>

</div>
<div class="col-md-12 text-center">
		<%= link_to "Contact", contact_path, class: "btn btn-lg btn-primary center" %>
	</div>
</div>

app/views/pages/contact.html.erb
<h1>Would you like to work together?</h1>

<hr>

<div class="row">
	<div class="col-md-6">
		<h3>Office Address</h3>

		<p>Gopalan Millennium Tower, Kundalahalli Colony, Brookefield</p>
		<p> Bengaluru</p>
		<p>560037</p>

		<h3>Email</h3>

		<p><a href="mailto:sushmitha@gmail.com?subject=ProductContact" email me>Email me</a> </p>

		<h3>Phone</h3>

		<p><%= number_to_phone "9522386131" %></p>
	</div>

	<div class="col-md-6">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3326.944949124724!2d-111.92897748422938!3d33.502809380759025!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x872b0bbd35df8635%3A0xf873d55c2d4dc69a!2s7150+E+Camelback+Rd+%23444%2C+Scottsdale%2C+AZ+85251!5e0!3m2!1sen!2sus!4v1484796936675" width="350" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>

app/views/pages/home.html.erb
<div class="inner cover">
	<h1 class="cover-heading">Welcome.</h1>
	<p class="lead">Software development should not be a secret process, when I take on a new project I make it my goal to not only deliver a well crafted product but to also ensure that each stage of the process is fully communicated.</p>
	<p class="lead">
		<%= link_to "About", about_path, class: "btn btn-lg btn-primary" %>
	</p>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
<div class="col-md-6">
      <div class="form-group center">
        <%= form.label :title %><br>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group center">
        <%= form.label :description %><br>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class="form-group center">
        <%= form.label :price %><br>
        <%= form.text_field :price, class: 'form-control' %>
      </div>

      <div class="form-group center">
        <label class="btn btn-primary">
          Upload a main image<%= form.file_field :main_image, multiple: true, style: 'display:none;' %>
        </label>
      </div>

      <div class="form-group center">
        <label class="btn btn-primary">
          Upload a thumb image<%= form.file_field :thumb_image, multiple: true, style: 'display:none;' %>
        </label>
      </div>

    <div class="actions center">
      <%= form.submit 'save Product' , class: 'btn btn-primary btn-block'%>
    </div>
<% end %>

app/views/products/_product.html.erb
<div class= "card" >
  <%= image_tag product_img(product.thumb_image_url, 'thumb') unless product.thumb_image.nil? %>
  <p class= "card-text">
   <span><%= link_to product.title, product_path(product) %></span>
  </p>
</div> 

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="album text-muted">
<div class="container">
<%= render "shared/banner"%>

<%= render partial: 'product', collection: @products %>
<p class= "center">
	<%= link_to 'Create New Product', new_product_path, class: 'btn btn-primary' %></p>

</div>
</div>

app/views/products/new.html.erb
<div>
	<div class="col-md-6"><h1>New Product</h1></div>

		<%= render 'form', product: @product %>

		<%= link_to 'Back', products_path, class: "center" %>
	</div>
</div>

app/views/products/show.html.erb
<div class="container margin-top">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag product_img(@product.thumb_image_url ,'thumb') %>
    </div>

    <div class="col-md-5">
      <h1><%= @product.title %></h1>

      <hr>

      <em><%= @product.description %></em>

      <p><%=  @product.price %></p>

      <hr>


      <%= link_to 'Back', products_path %> |

        <%= link_to 'Edit', edit_product_path(@product) %> 
    
    </div>
  </div>
</div>

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
	<div class="inner">
		<p class="app-footer footer-style">&copy; Trika Technology 2019</p>
	</div>
</div>

app/views/shared/_banner.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="first-slide" src="https://neilpatel.com/wp-content/uploads/2015/04/ecommerce.jpg" alt="First slide">
      <div class="container">
        <div class="carousel-caption d-none d-md-block text-left">
          <h1>Welcome to shopping</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="second-slide" src="https://s3.envato.com/files/127214816/Book%20&%20Glasses%20Preview%20Image.jpg" alt="Second slide">
      <div class="container">
        <div class="carousel-caption d-none d-md-block">
          <h1>Another example headline.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="third-slide" src="https://images.pexels.com/photos/904616/pexels-photo-904616.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="Third slide">
      <div class="container">
        <div class="carousel-caption d-none d-md-block text-right">
          <h1>One more for good measure.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>